// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhXTmrJZKrSYbU5Xv508gE_JBAbilnyJ4',
    appId: '1:275703096192:web:68e56c6e6fe2dcb68b5765',
    messagingSenderId: '275703096192',
    projectId: 'school-app-ef824',
    authDomain: 'school-app-ef824.firebaseapp.com',
    storageBucket: 'school-app-ef824.firebasestorage.app',
    measurementId: 'G-7K4MBT0E0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpsHq_CE3XNKkWPIDbQRY_6e4xaxLyuiw',
    appId: '1:275703096192:android:841ad1efba3b176a8b5765',
    messagingSenderId: '275703096192',
    projectId: 'school-app-ef824',
    storageBucket: 'school-app-ef824.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf5DJOKnGug8SlmVxRl_R86xly-ojp_4E',
    appId: '1:275703096192:ios:1b33b92868272ff78b5765',
    messagingSenderId: '275703096192',
    projectId: 'school-app-ef824',
    storageBucket: 'school-app-ef824.firebasestorage.app',
    iosBundleId: 'com.example.schoolApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf5DJOKnGug8SlmVxRl_R86xly-ojp_4E',
    appId: '1:275703096192:ios:1b33b92868272ff78b5765',
    messagingSenderId: '275703096192',
    projectId: 'school-app-ef824',
    storageBucket: 'school-app-ef824.firebasestorage.app',
    iosBundleId: 'com.example.schoolApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhXTmrJZKrSYbU5Xv508gE_JBAbilnyJ4',
    appId: '1:275703096192:web:f0d34696d5e537fb8b5765',
    messagingSenderId: '275703096192',
    projectId: 'school-app-ef824',
    authDomain: 'school-app-ef824.firebaseapp.com',
    storageBucket: 'school-app-ef824.firebasestorage.app',
    measurementId: 'G-MF0Y4NKB9J',
  );
}
