const List<String> countries = [
  'Afeganistão',
  'África do Sul',
  'Albânia',
  'Alemanha',
  'Andorra',
  'Angola',
  'Anguila',
  'Antígua e Barbuda',
  'Arábia Saudita',
  'Argélia',
  'Argentina',
  'Arménia',
  'Aruba',
  'Austrália',
  'Áustria',
  'Azerbaijão',
  'Bahamas',
  'Bangladesh',
  'Barbados',
  'Barém',
  'Bélgica',
  'Belize',
  'Benim',
  'Bermudas',
  'Bielorrússia',
  'Bolívia',
  'Bósnia e Herzegovina',
  'Botsuana',
  'Brasil',
  'Brunei',
  'Bulgária',
  'Burquina Faso',
  'Burundi',
  'Butão',
  'Cabo Verde',
  'Camarões',
  'Camboja',
  'Canadá',
  'Catar',
  'Cazaquistão',
  'Chile',
  'China',
  'Chipre',
  'Colômbia',
  'Comores',
  'Congo (Brazzaville)',
  'Congo (Kinshasa)',
  'Coreia do Norte',
  'Coreia do Sul',
  'Costa do Marfim',
  'Costa Rica',
  'Croácia',
  'Cuba',
  'Dinamarca',
  'Dominica',
  'Egipto',
  'El Salvador',
  'Emirados Árabes Unidos',
  'Equador',
  'Eritreia',
  'Eslováquia',
  'Eslovénia',
  'Espanha',
  'Estados Unidos',
  'Estónia',
  'Etiópia',
  'Filipinas',
  'Finlândia',
  'França',
  'Gabão',
  'Gâmbia',
  'Gana',
  'Geórgia',
  'Gibraltar',
  'Grécia',
  'Granada',
  'Guatemala',
  'Guiana',
  'Guiné',
  'Guiné-Bissau',
  'Guiné Equatorial',
  'Haiti',
  'Holanda',
  'Honduras',
  'Hungria',
  'Índia',
  'Indonésia',
  'Irão',
  'Iraque',
  'Irlanda',
  'Islândia',
  'Israel',
  'Itália',
  'Jamaica',
  'Japão',
  'Jordânia',
  'Kosovo',
  'Kuwait',
  'Laos',
  'Lesoto',
  'Letónia',
  'Líbano',
  'Libéria',
  'Líbia',
  'Listenstaine',
  'Lituânia',
  'Luxemburgo',
  'Macedónia do Norte',
  'Madagáscar',
  'Malásia',
  'Malawi',
  'Maldivas',
  'Mali',
  'Malta',
  'Marrocos',
  'Mauritânia',
  'México',
  'Moçambique',
  'Mónaco',
  'Mongólia',
  'Montenegro',
  'Namíbia',
  'Nepal',
  'Nicarágua',
  'Níger',
  'Nigéria',
  'Noruega',
  'Nova Zelândia',
  'Omã',
  'Países Baixos',
  'Paquistão',
  'Panamá',
  'Paraguai',
  'Peru',
  'Polónia',
  'Portugal',
  'Quénia',
  'Quirguistão',
  'Reino Unido',
  'República Centro-Africana',
  'República Checa',
  'República Dominicana',
  'Roménia',
  'Ruanda',
  'Rússia',
  'São Cristóvão e Nevis',
  'São Tomé e Príncipe',
  'São Vicente e Granadinas',
  'Seicheles',
  'Senegal',
  'Serra Leoa',
  'Sérvia',
  'Singapura',
  'Síria',
  'Somália',
  'Sri Lanka',
  'Suécia',
  'Suíça',
  'Suriname',
  'Tailândia',
  'Taiwan',
  'Tajiquistão',
  'Tanzânia',
  'Timor-Leste',
  'Togo',
  'Trindade e Tobago',
  'Tunísia',
  'Turcomenistão',
  'Turquia',
  'Ucrânia',
  'Uganda',
  'Uruguai',
  'Uzbequistão',
  'Vanuatu',
  'Vaticano',
  'Venezuela',
  'Vietname',
  'Zâmbia',
  'Zimbabué',
];
